### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by omar-khaium** [yahu1031/serverpod_ext#7]
Getting this error on VS Code, while running `flutter pub get` in terminal

<img width="1081" alt="Screenshot 2023-07-07 at 3 58 00 PM" src="https://github.com/yahu1031/serverpod_ext/assets/40541185/ffb4d63f-469f-4fb0-99e5-c0485cdd42be">

**Comment by yahu1031** [comment]
Thanks @Omar-Khaium will be fixing it soon

**Comment by yahu1031** [comment]
Fixed at [dab30d5](https://github.com/yahu1031/serverpod_ext/commit/dab30d56fae1d5f35c99e629709b49fedb4f6a9d)
